// <auto-generated />
namespace QuartzWebTemplate.Quartz
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddQuartzIndexes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddQuartzIndexes));
        
        string IMigrationMetadata.Id
        {
            get { return "201703271206132_AddQuartzIndexes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
